### ISSUE TITLE
Opening subghz read settings causes unresponsiveness

### ISSUE THREAD

**Issue by ZProLegend007** [Next-Flip/Momentum-Firmware#101]
### Describe the bug.

When opening the subghz app and going to read, the config, after waiting a couple seconds the flipper becomes unresponsive. (Does not happen on read RAW config.) I am on dev firmware, commit c4c1870.

### Reproduction

Turn on flipper, open subghz through any method, go to read, then config, then wait a couple seconds.

**Comment by WillyJL** [comment]
what modulation are you using? and are you using an external module? do you have a custom subghz configuration file? if so, share it

**Comment by ZProLegend007** [comment]
No custom configuration file or external module, I think it's on HND_1 modulation atm.

**Comment by ZProLegend007** [comment]
Funny you mention modulation... after quickly switching modulations the issue is gone. Quite odd...

**Comment by ZProLegend007** [comment]
It's worth noting the there is slight noticeable lag in the config menu...

**Comment by ZProLegend007** [comment]
Aaand it’s back, sorry for the spew of comments. The issue seems intermittent.

**Comment by WillyJL** [comment]
its hard to diagnose like this. try on a freshly formatted sd card, or different sd card altogether

**Comment by ZProLegend007** [comment]
I tried a fresh install. It seems to only happen when the modulation is set to HND_1.

**Comment by WillyJL** [comment]
Indeed, HND_1 modulation was problematic and had too high data rate for flipper hardware and current protocols set. Removed in Unleashed and here too. Can of course be readded if you have specific needs for it by using settings user file.

**Comment by WillyJL** [comment]
Just gonna keep open until release since it's still in 004 :D
