### ISSUE TITLE
flipper crashed when closing unitemp

### ISSUE THREAD

**Issue by ldxjy** [Next-Flip/Momentum-Firmware#108]
### Describe the bug.

flipper crashed when closing unitemp.
MNTM-DEV-ED57426
I deleted all sensors, still crashed when closing unitemp.
![Screenshot-20240424-142935](https://github.com/Next-Flip/Momentum-Firmware/assets/58037622/84f25aeb-1cbe-4041-bffd-aae04737e76b)

### Reproduction

1.run unitemp
2.close unitemp
3.flipper crashed and rebooted.

**Comment by WillyJL** [comment]
Fix was released in [mntm-002](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-002)
