### ISSUE TITLE
flipper freezing when add sensor[dev-a83845ae,unitemp]

### ISSUE THREAD

**Issue by ldxjy** [Next-Flip/Momentum-Firmware#115]
### Describe the bug.

flipper-z-f7-update-mntm-dev-a83845ae
flipper freezing when adding sensor

### Reproduction

1,open unitemp
2,add sensor
3,choose sensor type
4,choose save
5,flipper freezing

**Comment by WillyJL** [comment]
Can't replicate, please try on [mntm-002](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-002)

**Comment by WillyJL** [comment]
still cant replicate, try on newer version, maybe try to format sd card if it still happens, if still nothing write an update here please
