### ISSUE TITLE
All sub ghz frequencies blocked

### ISSUE THREAD

**Issue by Messha777** [Next-Flip/Momentum-Firmware#128]
### Describe the bug.

Since update all subghz frequencies are blocke, lost region provisioning

### Reproduction

Switch on

**Comment by WillyJL** [comment]
Need to update with qflipper or web updater to provision the region file. Or you can bypass region in momentum > protocols > subghz bypass region

**Comment by WillyJL** [comment]
It's almost as if the error screen tells you exactly what you need to do to fix the issue, nifty isn't it?

**Comment by Messha777** [comment]
I was able to fix this by region bypass. Now whenever I read a raw signal
the spl number doesn't move up and it's not saving the signal or saving
such a small timeframe that it can't be sent.

**Comment by WillyJL** [comment]
you need to lower your threshold value, also theres probably no signal being transmitted so no samples being collected

**Comment by apertureless** [comment]
> It's almost as if the error screen tells you exactly what you need to do to fix the issue, nifty isn't it?

Well, to be fair, it tells you you have to reinstall the firmware using web updater.  I installed it over qFlipper which was confusing at first.

**Comment by WillyJL** [comment]
it says "Reinstall firmware with Web/App". qflipper is a flipper companion app. reinstalling with qflipper fixes the issue too. the point is, region file is missing, reinstalling firmware with webupdater / qflipper / mobile app will fix it. because these methods will deploy the region data file.
