### ISSUE TITLE
Alarm Clock Function

### ISSUE THREAD

**Issue by MrBreadWater** [Next-Flip/Momentum-Firmware#129]
### Description of the feature you're suggesting.

We have a nightstand clock app, but no alarm? I feel like an alarm feature would be trivial to implement and a great little upgrade to the nightstand clock. 

### Anything else?

Honestly it wouldnt even need to run in the background or anything, just go off at the set time if you have have the clock open.

**Comment by StellarStoic** [comment]
I've been waiting for this for more than a year already and it boggles my mind why this hasn't been added by the official flipper team. 

There's a countdown app which triggers an alarm. 
We have 2 clock apps and none of them have an alarm 🤦🏻

**Comment by WillyJL** [comment]
@Zakrzewiaczek in #184:

> In the application, you can add alarms, which you can set a name for.
>
> => We set when the alarm should go off (time and day/days of the week) and confirm.
>
> Even if Flipper Zero is locked, the alarm will ring (this can be turned off in Momentum settings). Additionally, in the application, you can turn vibrations on and off and set the alarm sound.

**Comment by WillyJL** [comment]
https://github.com/flipperdevices/flipperzero-firmware/pull/3906

**Comment by stefanodelbosco** [comment]
> [flipperdevices/flipperzero-firmware#3906](https://github.com/flipperdevices/flipperzero-firmware/pull/3906)

Merged 2 day ago

**Comment by WillyJL** [comment]
yeah, and im merging it in #287 , already works great

**Comment by WillyJL** [comment]
now merged into dev branch, can use it in dev build. will be in 008 shortly

**Comment by WillyJL** [comment]
available in [mntm-008](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-008)
