### ISSUE TITLE
jammer 125 khz

### ISSUE THREAD

**Issue by npbk21** [Next-Flip/Momentum-Firmware#130]
### Description of the feature you're suggesting.

Is it possible to add a 125Khz jammer feature to the Flipper Zero?

**Comment by WillyJL** [comment]
What would that even achieve? If you want to prevent other cards from being scanned you can also just... cover the reader... and physically stop other peoples hands when putting up their card... it's not like you could do this from a distance...

Jamming isn't cool generally speaking and isn't some magic things that solves all your problems, stop being skids please
