### ISSUE TITLE
Apps (hub) in companion app incompatible firmware

### ISSUE THREAD

**Issue by Figure-itout** [Next-Flip/Momentum-Firmware#134]
### Describe the bug.

When you try to install/update apps with the mobile companion app you get a message to update the firmware.
momentum 001 works to install (not updating), momentum 003 give the error.
![Screenshot companion app](https://github.com/Next-Flip/Momentum-Firmware/assets/126983437/aa7810ac-4213-4dfb-a3f9-b91306b3b213)

### Reproduction

@Flipper
1. Switch on bluetooth

@Companion app
1. Connect to flipper
2. go to tab Hub
3. go to Apps

### Target

mntm-003

### Anything else?

Updating apps also didn't work with mntm-001.
Tried stock firmware 0.101.2, works fine, even updating apps.
Mobile phone is Motorola Edge 30 neo, Android 14.
Companion app is latest, version 1.6.8.1419

**Comment by Drotnip** [comment]
I've been having the same issue started 2 days ago. I factory wiped and reinstalled ofw and it works. Custom fw does not.

**Comment by WillyJL** [comment]
The api version changed. It works in dev build.

**Comment by WillyJL** [comment]
update to mntm-004
