### ISSUE TITLE
Customize the infrared remote button's positions on the screen using tables

### ISSUE THREAD

**Issue by Questwalker** [Next-Flip/Momentum-Firmware#141]
### Describe the enhancement you're suggesting.

Currently, custom infrared remotes only display their button in a long list on the screen. This is a unattractive way to sort the buttons, so I propose that some optional settings `row`, `column`, `rowspan`, and `columnspan` can be added to each button that will allow users to customize the positions of the buttons on the screen using a table-like system.

These settings should only be optional, in order to support backward compatibility.

### For example:
```
Filetype: IR signals file
Version: 1
# 
name: POWER
# 
name: Vol+
column: 0
columnspan: 1.5
# 
name: Vol-
column: 1.5
columnspan: 1.5
# 
name: SOURCE
column: 0
columnspan: 2
# 
name: MT
column: 2
# 
name: OK
column: 0
row: 3
rowspan: 2
# 
name: RE
row: 3
column: 2
# 
```
Would create something similar to this:

<img width="128" alt="menu2" src="https://github.com/Next-Flip/Momentum-Firmware/assets/94035647/9d5d0eee-36de-4e4f-849d-3ad8dd511c0f">

### Anything else?

I have created this to mimic the ways other graphics tools create tables. I understand if this kind of approach is not possible, but I would at least like some way to compact and arrange the buttons on the remote interface in order to make the experience easier to use.

**Comment by WillyJL** [comment]
There's quite a few apps that make infrared signals easier to use, check out Xremote, Quac!, CrossRemote, IR Remote. In regards to this feature request in particular, I think it's too much complexity for the added benefit it brings, considering those apps I mentioned already provide good alternative approaches. It's a no from me, but feel free to ask upstream if you're not satisfied with the alternatives

**Comment by ifuchs** [comment]
You mentioned Quac!. I have Momentum-3 installed and the Quac! found under Apps/SubGhz crashes when run with a null pointer dereference.

**Comment by WillyJL** [comment]
Quac is in apps > tools, also please update to version 004
