### ISSUE TITLE
asset packs broken

### ISSUE THREAD

**Issue by dontshome** [Next-Flip/Momentum-Firmware#149]
### Describe the bug.

whenever i add assest packs to my flipper they show up but dont actually change to anything but the momentum and basic ones

### Reproduction

put sd card if flipper
add asset pack
unplugged and add to flipper
change asset pack
return to home screen
hasnt updated

**Comment by WillyJL** [comment]
What pack did you install and how did you install it and how did you select it?

**Comment by dontshome** [comment]
I installed all packs but the problem was they were in a folder in a folder so it couldn't read it proper they are working now
