### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by derskythe** [Next-Flip/Momentum-Firmware#150]
### Describe the bug.

You have leakage here, the furi_string didn't deallocated
https://github.com/Next-Flip/Momentum-Firmware/blob/f6c59a9e762dbfbf446afa90c8cf0fe16044df11/applications/system/findmy/findmy_state.c#L19

### Reproduction

1. Open source
2. Do what you want

### Target

All

### Logs

```Text
None
```

### Anything else?

None

**Comment by WillyJL** [comment]
good catch, thanks!
