### ISSUE TITLE
Flipper Zero battery low screen disappears

### ISSUE THREAD

**Issue by Mason9667** [Next-Flip/Momentum-Firmware#151]
### Describe the bug.

When Flipper Zero hits 0% battery charge, a screen pops up asking the user if they want to cancel the shutdown, acknowledge the shutdown, or shutdown now. However, the screen disappears, not allowing the user to make a choice. The Flipper Zero then defaults to shutting down in 90s.

### Reproduction

1. Flipper Zero hits 0% battery charge. 
2. Screen appears that asks the user what they want to do
3. Screen disappears after 1-2s 
4. User cannot make a choice, and Flipper Zero turns off in 90s.

https://github.com/Next-Flip/Momentum-Firmware/assets/124535943/596da1f9-f64f-428e-933f-e1f7e5b15de9

**Comment by Mason9667** [comment]
Forgot to mention, the bug only happens when Flipper Zero is restarted

**Comment by Mason9667** [comment]
What additional info is needed?

**Comment by WillyJL** [comment]
Label means that it's not clear yet what is happening or how to fix it. Either give any info you can think is relevant, or we will eventually look into it with the info you already provided

**Comment by Mason9667** [comment]
The battery low screen disappears when it isn't supposed to. I can't make a choice regarding the shutdown, because the screen disappears too soon. The above video shows this happening.

**Comment by WillyJL** [comment]
@I-Flip-Zeros can you please try on latest dev build? many things changed related to power service

**Comment by Mason9667** [comment]
Yeah, updating now. I'll drain the battery and let you know if the bug is fixed.

**Comment by Mason9667** [comment]
Issue is resolved on dev 55fd64ee

**Comment by WillyJL** [comment]
Thank you!

**Comment by Mason9667** [comment]
👍
