### ISSUE TITLE
can't update apps on momentum 04 firmware after install

### ISSUE THREAD

**Issue by rcampbel3** [Next-Flip/Momentum-Firmware#158]
### Describe the bug.

I upgraded my flipper zero from unleashed -> xtreme -> momentum. After updating to momentum, I re-paired with bluetooth on my phone. I'm unable to update any of the flipper apps now through the phone app. I see the app updatre, I can click on it. The percentage goes to 100% and then just stays there

### Reproduction

turn flipper on. Open mobile app.
Go to mobile app.
select update all

### Anything else?

I didn't have this problem with unleashed or extreme... is it possible there's a permissions issue on the apps preventing update?

**Comment by WillyJL** [comment]
These are apps that are already included with momentum. Update momentum to update them. Or remove before updating via flipper app hub, but I strongly discourage this as apps included with momentum are tweaked to work best with momentum. Use the devbuild if you want the latest available.
