### ISSUE TITLE
[Sub-GHz] Weather Station app missing from mntm-005.

### ISSUE THREAD

**Issue by pleautaud** [Next-Flip/Momentum-Firmware#175]
### Describe the bug.

The Weather Station app is missing from the Sub-GHz Apps menu after updating to “mntm-005”.

The issue is present when installing from qFlipper (*.tgz package), or the Web Updater.

### Reproduction

1. Update Flipper to “mntm-005”.
2. Turn on the device
3. Open main interface (menu)
4. Select “Apps” submenu
5. Select “Sub-GHh” submenu.
6. Weather Station app not present.

**Comment by WillyJL** [comment]
This is intentional: weather station protocols are supported in main "Sub-GHz" app on momentum
