### ISSUE TITLE
storage.mkdir() doesn't work on virtualMount

### ISSUE THREAD

**Issue by khimaros** [Next-Flip/Momentum-Firmware#181]
### Describe the bug.

take for example this JS script:

```
let usbdisk = require("usbdisk");
let storage = require("storage");
let image = "/ext/example.img";
usbdisk.createImage(image, 32 * 1024 * 1024);
storage.virtualInit(image);
storage.virtualMount();
storage.mkdir("/mnt/payload/");
storage.copy("/ext/example.txt", "/mnt/payload/example.txt");
```

the `storage.copy()` fails because `/mnt/payload/` doesn't exist.

### Reproduction

1. add the script above to a file in scripts
2. launch the script

**Comment by WillyJL** [comment]
Trailing slashes are not supported on flipper. It's mkdir /mnt/payload

**Comment by khimaros** [comment]
thank you, that was the issue.

a bit off topic, but do you know if there is a way to `storage.remove()` recursively or otherwise to `storage.copy()` in a way that merges into an existing directory?

**Comment by WillyJL** [comment]
not at this time. expanding the features of storage module is on the todo list but not high in priority
