### ISSUE TITLE
Alarm clock app (clarification of issue #129)

### ISSUE THREAD

**Issue by Zakrzewiaczek** [Next-Flip/Momentum-Firmware#184]
### Description of the feature you're suggesting.

**In the application, you can add alarms, which you can set a name for.** 

=> We set when the alarm should go off (time and day/days of the week) and confirm. 

Even if Flipper Zero is locked, the alarm will ring (this can be turned off in Momentum settings). Additionally, in the application, you can turn vibrations on and off and set the alarm sound.

**Comment by Zakrzewiaczek** [comment]
This is a clarification of how the Alarm app works (#129 issue)

**Comment by WillyJL** [comment]
no reason for a separate issue, a comment in the original request is more appropriate.
