### ISSUE TITLE
Momentum Firmware LCD Brightness Issue on Flipper Zero

### ISSUE THREAD

**Issue by Allister1153** [Next-Flip/Momentum-Firmware#188]
### Describe the bug.

Issue Summary:

When setting the LCD screen brightness to 50%, the device does not retain the set brightness during the boot sequence. During the boot-up process, the screen momentarily flashes at 100% brightness before returning to the configured brightness (50%) once fully booted. This behavior is different from the Unleashed firmware, where the screen brightness remains consistent throughout the entire boot-up process.

Expected Behaviour:

The screen should maintain the user-defined brightness level (e.g., 50%) consistently during the entire boot sequence, including during power-on and boot-up. This would prevent the brief flash at 100% brightness, improving user experience, especially in low-light environments where sudden flashes can be disruptive.

Behaviour:

1. The user sets the screen brightness to 50%.

2. When powering on the Flipper Zero, the screen flashes at 100% brightness during the boot sequence.

4. After the device fully boots, the screen returns to the user-defined brightness (50%).

Comparison with Unleashed Firmware:
In the Unleashed firmware, the screen brightness remains at the user-defined level throughout the entire boot process, without any brief flashes at maximum brightness.

Impact:

This issue, while it’s not critical, affects the overall user experience, especially in low-light conditions where sudden brightness increases can be uncomfortable.

### Reproduction

Steps to Reproduce:

1. Set the screen brightness to 50% within the Momentum firmware settings.

2. Power off the device.

3. Power the device back on and observe the screen brightness during the boot-up sequence.

### Target

Momentum Firmware Development Team

**Comment by WillyJL** [comment]
nothing to do about this: handling of brightness happens in notification service, and notification service (like all services) is loaded after boot splashscreen. this is intentional, because during splashscreen also happens file migration, which allows retaining files from older versions due to changed file paths over multiple updates
