### ISSUE TITLE
SubGhz: misspelling in .sub file for GPS coordinates

### ISSUE THREAD

**Issue by polaramike** [Next-Flip/Momentum-Firmware#190]
### Describe the bug.

The coordinates in the .sub file have a typo: The correct spelling is 'Latitude' rather than 'Latitute' :-)

### Reproduction

Just record a signal and look inside the saved .sub file. No GPS needed to reproduce.

**Comment by WillyJL** [comment]
Yeah were aware but changing it doesn't bring any benefit, while it would mean breaking older files or adding more code to support them. For now it stays like this )
