### ISSUE TITLE
Font Packager From .ttf?

### ISSUE THREAD

**Issue by GameLord2011** [Next-Flip/Momentum-Firmware#193]
### Describe the enhancement you're suggesting.

Add funconality for packaging fonts from .ttf to .c

**Comment by WillyJL** [comment]
no, its not that simple. it requires a lot of manual work and verification and tweaking to make fonts look good. talking sasquach has a guide on youtube. but an automatic tool does not make sense for this, or atleast "put .ttf into an asset pack and compile" definitely does not make sense. if you wish to make an external tool that converts fonts with parameters and so on for manual tweaking sure, but this will not be part of automatic conversion in asset packer
