### ISSUE TITLE
Webapp Updater Broken

### ISSUE THREAD

**Issue by KorruptedPineapple** [Next-Flip/Momentum-Firmware#198]
### Describe the bug.

Attempting to navigate to https://momentum-fw.dev/update/ gives a "ERR_QUIC_PROTOCOL_ERROR" (404?)

### Reproduction

To to webpage

**Comment by WillyJL** [comment]
no, not 404. this is your browser / dns / internet provider / router / antivirus blocking the website.

**Comment by ZProLegend007** [comment]
If you are using chrome then go to chrome://flags and search for QUIC and disable the QUIC protocol option.
