### ISSUE TITLE
Keep getting sad animations

### ISSUE THREAD

**Issue by Anonymous3-a** [Next-Flip/Momentum-Firmware#199]
(By the way, there should be a issue template for questions.)  
I keep getting sad/angry animations, but my flipper is happy, I checked. Any way to make it not do that? I have "Unlock Animations" on.

**Comment by WillyJL** [comment]
disable unlock animations. the purpose of unlock animations is precisely to ignore mood and level checks

**Comment by Anonymous3-a** [comment]
Oh, ok. Thanks!
