### ISSUE TITLE
Keybinds Setup is broken!

### ISSUE THREAD

**Issue by VVolfCZ** [Next-Flip/Momentum-Firmware#202]
### Describe the bug.

The 'Remove Keybind' function is not working. The key still performs the original function! The issue occurred with version MNTM-006.

### Reproduction

1.settings 2.desktop 3.Keybinds setup 4.Press/Hold 5.Right(or left or anything else) 6.Remove Keybind 7.Keybind not removed!!!

**Comment by WillyJL** [comment]
Yep, this is fixed in dev branch
