### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by GameLord2011** [Next-Flip/Momentum-Firmware#209]
### Describe the enhancement you're suggesting.

switch underscore with space (for enhanced sub-ghz chat and whatnot)

**Comment by WillyJL** [comment]
for consistency, sorry but no it will stay as is

**Comment by GameLord2011** [comment]
It's that stuff like "Hey_bro_what's_up" looks weird.

**Comment by WillyJL** [comment]
That's why you can hold the ok button instead of pressing it, and it will produce a space instead of an _

**Comment by GameLord2011** [comment]
k
swap those?

**Comment by WillyJL** [comment]
As I said, no for consistency.

**Comment by GameLord2011** [comment]
k
