### ISSUE TITLE
NFC Dectect Reader Enhancement Request

### ISSUE THREAD

**Issue by AthenaCN** [Next-Flip/Momentum-Firmware#214]
### Describe the enhancement you're suggesting.

I have a request about enhancing the functions of the NFC Dectect Reader.
[https://github.com/Next-Flip/Momentum-Firmware/tree/dev/applications/main/nfc](url)
When I use this function to dectect a kind of reader which is connected to a server with network and intend to get key, the reader always return me a fake one. I think about it, it maybe read the NFC card's UID first, if the UID is stored in the database, it will return the vaild key to the nfc card to unlock sectors. Probably one card to one key.
I found the current functions of the NFC Dectect Reader is generate a random nfc card via furi. So I have a request of the functions that can use a specific card UID to dectect reader, maybe it can allow us to select card from saved file.
Please forgive me for I have no skills and abilities to program this function myself. Thank you all in advance.

**Comment by WillyJL** [comment]
So, you asked for the feature before checking if it exists.

It's not a "fake key", it's called UID derived key, and many systems use it for security.

If you opened a saved file for a Mifare classic card, you would have seen there is a detect reader option on it too.
