### ISSUE TITLE
BadKB and BadBT Keyboard Layout Bug - MNTM-007

### ISSUE THREAD

**Issue by AztecCodes** [Next-Flip/Momentum-Firmware#219]
### Describe the bug.

When I use BadKB or BadBT and select the keyboard layout which is in my case de-CH, it doesn't work correctly.
I tried other layouts too and have the same problem.
Now this bug appeared a few versions earlier, was fixed and now it is here again.

**Version:** MNTM-007.

### Reproduction

1. Start BadKB on your Flipper Zero
2. Select your keyboard layout and run the test payload
3. You will see that the symbols are wrong

I attached the text file of the demo_windows payload with de-CH.
[Hello World!.txt](https://github.com/user-attachments/files/17009869/Hello.World.txt)

### Anything else?
This problem was fixed in an earlier version and now reoccurs. It also appeared on Unleashed, but was also fixed there. If the current Unleashed version has this bug I don't know yet.

Also it seems like that the wrong symbols change even when I use the same payload.

_No response_

**Comment by leow149** [comment]
Did you find a solution for this? I'm having similar issues with the de-DE layout on Win11

**Comment by WillyJL** [comment]
you have no way of knowing if youre having similar issue, the original issue here did not have any details on what actually goes wrong, just "does not work correctly" which could mean 1000 different things.

if you want help provide details on what happens, what should happen, and how youre doing it

**Comment by AztecCodes** [comment]
@leow149 @Willy-JL 

The bug only appears in the standard windows text editor. Otherwise it works completely fine.

Because of that I closed the ticket.
