### ISSUE TITLE
SubGhz lost in mainmenu

### ISSUE THREAD

**Issue by ldxjy** [Next-Flip/Momentum-Firmware#22]
### Describe the bug.

I flashed Momentum-Firmware from unleashed 071e directly.
Now SubGhz has disappared in menu( click center button in desktop).
I tried to reset in MNTM -> interface -> Mainmenu -> Reset menu. after Reboot. SubGhz has appared in menu.
But, after I edited mainmenu in MNTM -> interface -> Mainmenu， subghz has disappared again. In MNTM -> interface -> Mainmenu I saw subghz is in the App List.
![Screenshot-20240311-112212](https://github.com/Next-Flip/Momentum-Firmware/assets/58037622/7a8d3ec4-9b45-461e-a8e7-22c7b076532e)
![Screenshot-20240311-112223](https://github.com/Next-Flip/Momentum-Firmware/assets/58037622/280da7cc-f40e-4fcd-966c-07bc0d22cb0f)

### Reproduction

1. reset in MNTM -> interface -> Mainmenu -> Reset menu
2. reboot
3. edit MNTM -> interface -> Mainmenu app list
4. SubGhz disappared

**Comment by WillyJL** [comment]
Yes I noticed this myself too, it was an oversight when migrating app names. It is fixed in latest dev branch, you can use the dev builds from the website. Unfortunately, if you already modified the menu app list, you will need to remove subghz and rfid, and add them again. Only these 2 were affected, due to changing the app names back to match ofw

**Comment by WillyJL** [comment]
The issue was that the main menu migrated the app names, but not the momentum app when editing the config file, so only after editing with the app it broke

**Comment by ldxjy** [comment]
> Yes I noticed this myself too, it was an oversight when migrating app names. It is fixed in latest dev branch, you can use the dev builds from the website. Unfortunately, if you already modified the menu app list, you will need to remove subghz and rfid, and add them again. Only these 2 were affected, due to changing the app names back to match ofw

ok, thanks, I will try dev firmware.

**Comment by WillyJL** [comment]
Fix was released in [mntm-002](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-002)
