### ISSUE TITLE
Mutancode not in the menu

### ISSUE THREAD

**Issue by DanielAlcon** [Next-Flip/Momentum-Firmware#221]
### Describe the bug.

Mutancode is missing from the menu for adding new SubGHz codes manually.

### Reproduction

1- Sub-GHz menu
2- Add Manually
3- Search for mutancode (if I'm not mistaken it should be something like KL: mutancode)

**Comment by WillyJL** [comment]
And on what basis were you expecting it to be there? Because I've never heard of that name

**Comment by DanielAlcon** [comment]
I saw it in the code and thought it was implemented but couldn't find it anywhere
![imagen](https://github.com/user-attachments/assets/f93ba824-8189-42a5-a77a-f39acf87bd1f)

**Comment by ZProLegend007** [comment]
The code snippet you've showed is from the keeloq protocol. Just use that, it's obviously in there.

**Comment by WillyJL** [comment]
Not sure if that would work, to add manually I believe you need the manufacturer's keys. KeeLoq can be detected easily, but without the manufacturer's encryption keys, which are different for each KeeLoq implementation, you can't tell what the counter is and how to make a new remote (add manually)

**Comment by WillyJL** [comment]
closing as this is not posible to implement without manufaturer keys
