### ISSUE TITLE
No : on Keyboard

### ISSUE THREAD

**Issue by Choder7** [Next-Flip/Momentum-Firmware#222]
### Describe the enhancement you're suggesting.

I've searched it multiple times, but couldn't seem to find the : Character, _I would want to use it for the CLI to change the Date and Time_

**Comment by WillyJL** [comment]
It's not available due to being an illegal character: on windows, files can't have it in the name, and since the keyboard is mostly used for filenames on flipper, it is disabled.

We have an api to allow the keyboard to show illegal characters, simply needs to be done for the cli app. Good catch.

**Comment by JoshTheBlack** [comment]
Has this been implemented?

**Comment by WillyJL** [comment]
No, hence why I had left it open

**Comment by Choder7** [comment]
Oops

**Comment by WillyJL** [comment]
fixed in [mntm-008](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-008)
