### ISSUE TITLE
Update stuck at 99 %

### ISSUE THREAD

**Issue by shivagnihotri** [Next-Flip/Momentum-Firmware#223]
Updating from official firmware 1.0.1 to mntm-007 keeps staying stuck at 99 %. What to do? 🙏

**Comment by Anonymous3-a** [comment]
Where is it stuck? Can you give a picture?

**Comment by shivagnihotri** [comment]
Yes. It just stays at 99 % forever.

**Comment by Choder7** [comment]
I updated though WebUpdater and it worked fine, if you have the option, maybe try that.

**Comment by WillyJL** [comment]
Try restarting the flipper by holding left and back a couple seconds. Also format the sd card if it keeps not working, backup files that you need first though

**Comment by shivagnihotri** [comment]
Problem solved! Thank you all for your assistance. The transmission finally worked quick and fast with [qFlipper](https://flipperzero.one/update). Momentum installing as I type. Excitement!

Thank you to all developers here. You're awesome. 🥰
