### ISSUE TITLE
Play Flipper sound on Phone/Earbuds

### ISSUE THREAD

**Issue by Choder7** [Next-Flip/Momentum-Firmware#229]
### Description of the feature you're suggesting.

If it's possible to do so, and not too elaborat, it would be great if you could hear the sound of the Flipper on your Phone, which you can then connect to earbuds.

I would use it for the SubGhZ App to locate a signal, or for Walkie Talkie. It would be so much more comfortable.

### Anything else?

Just a feature request, doesn't have to be coded if it is to elaborate or hardly possible. Thanks, Great Work! 😃👍

**Comment by WillyJL** [comment]
This would need to be baked into RPC somehow, and likely would be very laggy. Regardless, it is out of scope of this project since we don't deal with companion apps. Suggest this to the official firmware repo, but I must warn you it will likely be a no there too.
