### ISSUE TITLE
Potential GPLv3 Violation and Website Plagiarism by FlipperCN

### ISSUE THREAD

**Issue by kalicyh** [Next-Flip/Momentum-Firmware#232]
Dear Momentum developers,

I recently discovered that a project named "FlipperCN" (https://flippercn.com) appears to be violating the GPLv3 license of your project. They have seemingly copied parts of your code but have not made their modifications public as required by the GPLv3. In addition, their website appears to directly plagiarize your official website (https://momentum-fw.dev/), including design and content.

Here are the issues I have identified:
1. **Code plagiarism**: FlipperCN seems to have reused parts of your source code without providing proper attribution or releasing their modifications as open source, which is a clear violation of the GPLv3 license.
2. **Website plagiarism**: The design and content of FlipperCN's website closely resemble those of your website, including sections of text and images.

I have attached screenshots comparing their website to yours, along with examples of similar code sections for your reference. I believe this issue should be addressed to protect your intellectual property and maintain the integrity of the open-source community.

Thank you for your attention to this matter.

| Evidence | Momentum | FlipperCN |
|----------|----------|----------|
| Github | https://github.com/Next-Flip/Momentum-Firmware | https://github.com/ZhaiRenGaiZaoJia/FlipperZero-CN-Firmware |
| Website | https://momentum-fw.dev/ | https://flippercn.com |
| Screenshot | ![CleanShot 2024-09-23 at 11 41 02@2x](https://github.com/user-attachments/assets/bac3eb26-3cae-47a8-905e-47b5f8e605fa) | ![CleanShot 2024-09-23 at 11 42 19@2x](https://github.com/user-attachments/assets/476cd938-7ec8-416d-a26d-9a11fa782d64)|
| | ![CleanShot 2024-09-23 at 11 41 31@2x](https://github.com/user-attachments/assets/d3278854-d9e5-4902-ab41-9ce5e291d078) | ![CleanShot 2024-09-23 at 11 42 31@2x](https://github.com/user-attachments/assets/ce654779-442a-4cef-b421-557314db0450) |
||![CleanShot 2024-09-23 at 11 41 48@2x](https://github.com/user-attachments/assets/4c5af7af-6140-4a36-8bd5-3ae9020e268f)|![CleanShot 2024-09-23 at 11 42 40@2x](https://github.com/user-attachments/assets/0a98d57d-c531-49ea-80e7-2160b8f93d6c)|
||![CleanShot 2024-09-23 at 11 41 59@2x](https://github.com/user-attachments/assets/6d39e61c-603d-4968-b643-aace33fc425e)|![CleanShot 2024-09-23 at 11 42 49@2x](https://github.com/user-attachments/assets/6f0acca2-99b6-4735-a9b1-a2864e24d1c4)|
|||![CleanShot 2024-09-23 at 11 43 31@2x](https://github.com/user-attachments/assets/d09807a1-b441-4ca4-922b-e824dcd6936a)|
|||![CleanShot 2024-09-23 at 11 43 43@2x](https://github.com/user-attachments/assets/7498ce3d-7797-4627-a188-8f9445ade0b1)|
|||![CleanShot 2024-09-23 at 12 02 37@2x](https://github.com/user-attachments/assets/8863f515-2ca7-4535-999e-526d809e99b1)|

**Comment by WXLN** [comment]
Dogs and mice are meddling in other people's affairs.
However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others

**Comment by kalicyh** [comment]
> Dogs and mice are meddling in other people's affairs.
> However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others

I am stating the facts, and what are you doing? What do you take the GPL 3.0 open-source license for?

**Comment by kalicyh** [comment]
> Dogs and mice are meddling in other people's affairs.
> However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others

Moreover, I have better code, https://github.com/kalicyh/Momentum-Firmware, so why use his code?

**Comment by kalicyh** [comment]
> Dogs and mice are meddling in other people's affairs.
> However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others


What you're saying completely misunderstands the core spirit of the GPL 3.0 open-source license. Under the GPL 3.0, any work that modifies and redistributes GPL-licensed code must follow the same open-source principles, meaning the author is obligated to provide the source code when publishing derivative works. This is not "meddling" or "smearing" but a part of the transparency and sharing spirit that protects the open-source community. If you choose to use GPL-licensed code, you must respect and comply with the GPL terms, rather than unilaterally deciding whether or not to release modified code.

**Comment by WXLN** [comment]
是什么原因你自己。明白。不想把你们的恶心事放到台面上。在国内搞不定，跑到外网来搞，如果你们的脑子和心思放在代码研究上，就不会惦记别人手上的东西了。傻逼

**Comment by kalicyh** [comment]
> 是什么原因你自己。明白。不想把你们的恶心事放到台面上。在国内搞不定，跑到外网来搞，如果你们的脑子和心思放在代码研究上，就不会惦记别人手上的东西了。傻逼

I don’t need anything from anyone else. My issue is with people violating the GPL 3.0 open-source license. If you had spent more time understanding the principles of open-source and respecting its terms, you wouldn’t be making baseless accusations. Trying to hide shady behavior won’t work, no matter where you do it—here or anywhere else.

**Comment by Nesriaaa** [comment]
> > Dogs and mice are meddling in other people's affairs.
> > However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others
> 
> Moreover, I have better code, https://github.com/kalicyh/Momentum-Firmware, so why use his code?

Based on the firmware downloaded from your link, I don’t think your firmware is of high quality. There are size differences in some fonts, and more importantly, the program runs into memory shortage issues. So, did you raise this issue to showcase your open-source spirit or to highlight your contributions to the Chinese firmware? I don’t believe that translating official firmware demonstrates any particular skill or technical ability. Additionally, there are reasons for not open-sourcing code, and forcing others to open-source has its own motives. Human genes are marked by selfishness and greed, which you perfectly embody. In summary, it’s like a dog catching mice—meddling in others’ business.

**Comment by ZProLegend007** [comment]
> > > Dogs and mice are meddling in other people's affairs.
> > > However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others
> > 
> > 
> > Moreover, I have better code, https://github.com/kalicyh/Momentum-Firmware, so why use his code?
> 
> Based on the firmware downloaded from your link, I don’t think your firmware is of high quality. There are size differences in some fonts, and more importantly, the program runs into memory shortage issues. So, did you raise this issue to showcase your open-source spirit or to highlight your contributions to the Chinese firmware? I don’t believe that translating official firmware demonstrates any particular skill or technical ability. Additionally, there are reasons for not open-sourcing code, and forcing others to open-source has its own motives. Human genes are marked by selfishness and greed, which you perfectly embody. In summary, it’s like a dog catching mice—meddling in others’ business.

You are a fake account that was literally made 1h ago, likely for the purpose of giving support to your other account. Chill out bro.

**Comment by kalicyh** [comment]
> > > Dogs and mice are meddling in other people's affairs.
> > > However, in reality, the author just doesn't want to give you his code, so you want to deliberately smear and force third-party authors to open source the code. Open source agreements don't mean you can make any choices on behalf of others
> > 
> > Moreover, I have better code, https://github.com/kalicyh/Momentum-Firmware, so why use his code?
> 
> Based on the firmware downloaded from your link, I don’t think your firmware is of high quality. There are size differences in some fonts, and more importantly, the program runs into memory shortage issues. So, did you raise this issue to showcase your open-source spirit or to highlight your contributions to the Chinese firmware? I don’t believe that translating official firmware demonstrates any particular skill or technical ability. Additionally, there are reasons for not open-sourcing code, and forcing others to open-source has its own motives. Human genes are marked by selfishness and greed, which you perfectly embody. In summary, it’s like a dog catching mice—meddling in others’ business.

First, I admit that the quality of the code is not very high, but it is based on the GPL 3.0 open-source license. I feel it is my obligation to make it public and contribute to the open-source community. Additionally, I have clearly indicated that this firmware is customized for my personal needs. I prefer to teach others how to modify and localize the firmware, rather than monopolize such knowledge. Anyone can propose better approaches, or even replace mine. However, if someone doesn't comply with the GPL 3.0 open-source license, it will only diminish the Flipper Zero ecosystem. I am happy to adhere to the GPL 3.0 license and hope more people will understand its value.

**Comment by WillyJL** [comment]
i heard from zhairen directly thanks to torron/zinongli mediating and getting us in touch. the situation seems more complicated than you make it out to be here. theres no official means of obtaining a real flipper zero in china, and many fakes being sold as "real", zhairen doesnt want to opensource his fork of momentum to prevent these fake flipper sellers from removing the warning that the flipper is counterfeit and so to protect buyers from being scammed with fake flippers. while this is not a valid excuse for violating gpl3, it is also not him trying to gatekeep the source for personal gain. ultimately, theres not much i can do here, and i dont need this drama around my project.
as for the similarities in the website design, he said it is because he admires what we built in momentum and doesnt want to take attention away from it, but rather popularize it and the only credit he wants to himself is translation.
all in all, i am not ok with him violating gpl3 of the project and will not endorse it in any way, but i will not intervene either. if someone else from the broader flipper community, since gpl3 is not only on momentum but all flipper firmware related projects, takes more of a problem with what zhairen is doing, then they can act out of their own initiative.
