### ISSUE TITLE
Feature request: desktop background energy save

### ISSUE THREAD

**Issue by vsvito420** [Next-Flip/Momentum-Firmware#242]
Stop animation on screen when not in use, or slow down?

Im not sure how much energy this will save

**Comment by Anonymous3-a** [comment]
If you want to save energy, just turn the flipper off. There's a power off on idle option in settings.

**Comment by WillyJL** [comment]
using deepsleep, which is the default configuration, flipper use 1.2ma while playing desktop animations. this means 1 month battery life. disabling desktop animations would not change this by much
