### ISSUE TITLE
Feature Request: Duplicate RFID/NFC notification

### ISSUE THREAD

**Issue by TheFilipcom4607** [Next-Flip/Momentum-Firmware#243]
### Describe the enhancement you're suggesting.

I would like to request a feature for momentum firmware that alerts users when they scan an NFC/RFID tag that has already been saved on the device. If a scanned tag matches one already stored, the device should notify the user with a message like “This tag has already been saved. Do you want to save it again?” This would help prevent accidental duplication of tags and make it easier to manage and organize saved tags.

### Anything else?

no

**Comment by WillyJL** [comment]
searching all saved files for a match is time consuming and error prone, i think this is out of scope sorry
