### ISSUE TITLE
Clean interface for the official Flipper Zero app store

### ISSUE THREAD

**Issue by AztecCodes** [Next-Flip/Momentum-Firmware#249]
### Description of the feature you're suggesting.

It would be great if Momentum would have a clean interface to the official Flipper Zero app store.

Currently pre-installed apps on Momentum are not shown in the App Store as "installed".
It would be great of pre-installed apps that are available in the app store are shown as "installed" and that you have the possibility to use the "Update" feature of the app store.

It would be nice if this works for browser and mobile.

**Comment by ZProLegend007** [comment]
A lot of apps that come with mntm are slightly modified and are updated to stay up to date with the firmware. This means they won't identify as the same apps as the ones in the App Store and if they were updated then the modifications would be overridden with the default app. It's just the way it is.
