### ISSUE TITLE
Evil Portal + Deauth at the same time

### ISSUE THREAD

**Issue by Choder7** [Next-Flip/Momentum-Firmware#252]
### Description of the feature you're suggesting.

Is it possible for the Flipper Zero with the WiFi Dev board to Deauth a network at the same time as Evil Portal is running?

### Anything else?

no

**Comment by WillyJL** [comment]
no, and this should be directed at an esp32 project not a flipper project.

best you can do is get a dual esp32 board liek the ones awok makes.
