### ISSUE TITLE
Tamagotchi app crashes flipper

### ISSUE THREAD

**Issue by JuanCarrlosJacome** [Next-Flip/Momentum-Firmware#27]
### Describe the bug.

Opening the tamagotchi app makes the screen go blank and a beeping sound that doesn't go away until rebooting the flipper 

### Reproduction

Opening tamagotchi app

**Comment by WillyJL** [comment]
that beeping is the beginning of the tamagotchi game afaik. if you dont see anything on screen, your save and/or rom might be corrupted. try deleting apps_data/tama_p1/save.bin

**Comment by JuanCarrlosJacome** [comment]
This solved the problem, thank you very much!
