### ISSUE TITLE
FlipperHTTP AND EvilPortal AND ESP32 Marauder available in the same time without WiFi DevBoard flashing

### ISSUE THREAD

**Issue by Tristen87** [Next-Flip/Momentum-Firmware#303]
### Describe the enhancement you're suggesting.

Currently both Marauder and Evil Portal are working perfectly fine. Strongly appreciate that, it is extremely useful. However, when tried to run FlipperHTTP it generates error "No WiFi Dashboard found". Would be any possibility to make all three working together without  re-flashing ESP32 DevBoard?

**Comment by WillyJL** [comment]
Unfortunately no it's not possible
