### ISSUE TITLE
BadKB doesn't write ñ or Ñ in spanish layout

### ISSUE THREAD

**Issue by iecxiv** [Next-Flip/Momentum-Firmware#307]
### Describe the bug.

Over bluetooth on android connection, doesn't write ñ or Ñ from string

### Reproduction

STRING ñ
STRING Ñ

Writes nothing on es_ES layout

### Target

Android

**Comment by WillyJL** [comment]
yeah, badusb scripts can only handle ascii characters. the purpose of keyboard layouts is to make it so the ascii characters map to the correct ones for the target computer, but it does not magically add support for non ascii characters.
by ascii, i mean specifically the original lower ascii range, up to character code 127, which does not include any accents or variations of letters, so it does not include ñ. if you absolutely require to type this character, you might be able to use `ALTSTRING ñ`, or `ALTCHAR 164`. please see here: https://github.com/Next-Flip/Momentum-Firmware/blob/dev/documentation/file_formats/BadUsbScriptFormat.md

**Comment by iecxiv** [comment]
On android does not work ALTSTRING or ALTCHAR
