### ISSUE TITLE
Secondary fonts are glitching.

### ISSUE THREAD

**Issue by GameLord2011** [Next-Flip/Momentum-Firmware#308]
### Describe the bug.

I am using a customized version of mntm-8 (all changes are in the cli so I'm pretty sure it isn't causing this) and the Watch dogs secondary font is not working, and it is switching to the default secondary font.

### Reproduction

1. Turn on flipper
2. change asset pack to _Watch Dogs_
3. open apps menu
4. open nfc app

### Target

Firmware

**Comment by WillyJL** [comment]
asset packs are intentionally disabled in very few select apps. nfc, mfkey and upython apps are very heavy apps and require as much ram as they can get, so disabling asset packs helps with memory issues for those apps

**Comment by GameLord2011** [comment]
k

**Comment by GameLord2011** [comment]
then what about the "nfc" and "rfid" icons in watch dogs?

**Comment by WillyJL** [comment]
:man_shrugging: its there and the nfc app doesnt use it. rfid app still uses asset packs so not sure why mention that. and the `NFC_dolphin_emulation_51x64` is actually used by the rfid app and the esubghz chat app too, so you still see it.

**Comment by GameLord2011** [comment]
sry read mfkey as rfid
