### ISSUE TITLE
JS: BadUSB keyboard layout support

### ISSUE THREAD

**Issue by notlucasdma** [Next-Flip/Momentum-Firmware#31]
### Description of the feature you're suggesting.

Can you add that you can switch between keyboard languages that i can use it because i am in germany and i cant realy use it effectifly

**Comment by WillyJL** [comment]
We plan to add the possibility to set a keyboard layout, check the projects tab.

**Comment by WillyJL** [comment]
as of #33 there is now `badusb.altPrint()` and `badusb.altPrintln()`, which allow layout-independent functionality __only on windows__. still plan to implement layouts, as that would work on macos, linux, android and ios too.

**Comment by WillyJL** [comment]
Was released in [mntm-002](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-002)
