### ISSUE TITLE
On android does not work ALTSTRING or ALTCHAR

### ISSUE THREAD

**Issue by iecxiv** [Next-Flip/Momentum-Firmware#312]
On android does not work ALTSTRING or ALTCHAR

_Originally posted by @iecxiv in https://github.com/Next-Flip/Momentum-Firmware/issues/307#issuecomment-2495650961_

**Comment by WillyJL** [comment]
not something we can fix. android does not support this. this is a windows feature.

**Comment by iecxiv** [comment]
Not possible to write ñ or Ñ on android...

**Comment by WillyJL** [comment]
:man_shrugging:

**Comment by iecxiv** [comment]
Thanks
