### ISSUE TITLE
Sub-GHz fire and forget mode

### ISSUE THREAD

**Issue by ventusz** [Next-Flip/Momentum-Firmware#313]
### Description of the feature you're suggesting.

What I found out is that although there is an auto save feature in the Sub-GHz app, after many signals it says that the memory is full and stops scanning.
IMO a switch would be great that could maybe show a statistics  page of the number of captured signal types during the session rather than the signals themselves. This way the flipper would not run out of memory and could continue recording signals "forever" without having to interact with it.

**Comment by WillyJL** [comment]
There is "del old signals when full", self explanatory

**Comment by ventusz** [comment]
My bad, should have used my eyes, thank you!
