### ISSUE TITLE
Remove Flipper - the game

### ISSUE THREAD

**Issue by leonardpitzu** [Next-Flip/Momentum-Firmware#318]
### Description of the feature you're suggesting.

I acknowledge the Flipper Game but how about adding the ability to fully remove it and make the Flipper Zero a plain, simple tool, without the game and toy aspect of it. Would also free up some resources...

**Comment by WillyJL** [comment]
We prefer to keep the flipper theme and functionality out of the box as it's how the product was designed and we appreciate that. For simplicity we also won't offer alternative releases of our firmware with different modifications. If you want you can make an asset pack to replace the dolphin icons with 0x0 pixel empty icons, but removing features like the dolphin leveling system would require editing firmware. How much would be saved on resources is debatable. But overall not something I plan on working on, you're free to make your own version of momentum with these things stripped.
