### ISSUE TITLE
I found out how to change the cli prompt.

### ISSUE THREAD

**Issue by GameLord2011** [Next-Flip/Momentum-Firmware#319]
1. Change the "CLI_PROMPT," and the "CLI_PROMPT_LENGTH," variables accordingly.
2. Build the firmware.
3. Flash the firmware.
4. Clone "flipperdivices/qFlipper," or "Next-Flip/qFlipper," and download all standalone build dependencies.
5. Edit line 20 of "backend/flipperzero/rpc/stoprpcoperation.cpp," and line 19 of "backend/flipperzero/rpc/skipmotdoperation.cpp" to match the new prompt.
6. Build qFlipper.
7. Done!

**Comment by GameLord2011** [comment]
Note, you will have to repeat steps 1-3 for Flipper firmware updates, and steps 4-6 for qFlipper updates, and for all computers you use qFlipper on.

**Comment by WillyJL** [comment]
Good job, but I don't understand why this is here. And it will break compatibility with other companion apps.
