### ISSUE TITLE
Unknow error when installing the momentum firmware

### ISSUE THREAD

**Issue by Trojankill** [Next-Flip/Momentum-Firmware#328]
### Describe the bug.

When installing the Momentum firmware, it returns an error at 11% load. ( firmware version 1.1.2 program version 1.3.3 ) Firmware version momentum 008

### Reproduction

1 install from file 
2 select the file flipper-z-f7-update-mntm-008.tgz
3 install

### Logs

```Text
[qFlipper-20241222-122058.txt](https://github.com/user-attachments/files/18221366/qFlipper-20241222-122058.txt)
```

### Anything else?

I bought it recently and apart from formatting the SD card and updating the firmware, I did not do it.

**Comment by Trojankill** [comment]
![Desktop Screenshot 2024 12 22 - 14 15 57 74](https://github.com/user-attachments/assets/9722d050-b6ea-490c-8253-9c90de54e469)
I read on the Internet that it has something to do with the driver DFU in FS mode
I also noticed that I can't install add-ons for flipper zero, custom firmware, or copy files firmware to an Sd card in the qFlipper program (I also tried to install the firmware via chrome, it gives the error)

**Comment by WillyJL** [comment]
Sounds like you have both qflipper and the web installer open. Only one can work at a time. Close the browser to be sure when you use qflipper

**Comment by Trojankill** [comment]
> Похоже, у вас открывается и qflipper, и веб-установщик. Вместе может работать только один из них. Закройте браузер, чтобы обеспечить надежность, когда используется qflipper

In the photo, I only used qflipper (the problem is that all the ways to install the momentum firmware on my computer don't work, and it takes a very long time to download on my phone) Even when closing the browser, the same problem

**Comment by Trojankill** [comment]
I solved the problem (the problem was in the sd card) I hope it helps someone.
The topic is closed
