### ISSUE TITLE
why does it make my micro sd's not work

### ISSUE THREAD

**Issue by dovydasa2** [Next-Flip/Momentum-Firmware#332]
### Describe the bug.

so when i use my flipper zero and try to turn it off  by holding left arrow and back button it just makes my Sd card's not work and two of them are just not working right now because of this.

### Reproduction

1.hold left arrow and back button 
2. it turns off for a few seconds 
3. your Sd card magickly doesn't work

**Comment by dovydasa2** [comment]
pls help

**Comment by 956MB** [comment]
> pls help

1. SD brand/size/format?
2. You had momentum flashed and working fine until rebooting with *left*+*back*?
3. Anything visible on screen during/after the reboot attempt?
4. When the flipper is off and you try turning it on again with *back* for 3 seconds, nothing happens at all?
5. Does the SD card show up and/or look fine plugged into your computer? Is it corrupted?

**Comment by dovydasa2** [comment]
1.i don't know/32 gb/wdym
2.it was working fine
3.nothing during reboot but there was the screen that said mounting Sd card failed immediately 
4. well the thing is that it just didn't turn off it rebooted immediately
5. it doesn't let my look and I'm going to add a screen shot just so you can see 
![Screenshot 2024-12-25 175026](https://github.com/user-attachments/assets/42473a2c-a5e5-4bfd-890b-b90e31376ee4)
btw i literally tried to format it every ware from my Nintendo to the pc and it always says that its unable

**Comment by Anonymous3-a** [comment]
Maybe a video of the MicroSD card being put in and left+back would help?

**Comment by dovydasa2** [comment]
Here it is https://we.tl/t-mV57C97qn9

**Comment by Anonymous3-a** [comment]
I meant what it looks like when the MicroSD card stops working. It also seems like you aren't verifying the MicroSD cards beforehand on a computer. In addition, it looks like a non-name brand MicroSD card. Those do not always support the low-power interface the Flipper Zero uses, so maybe there's something to do with that? The problem could also be something in the slot, like a tiny bit of metal that got in and is shorting some contacts.

Try:

 - Making sure the MicroSD chip worked before use in the flipper
 - Blowing into the MicroSD slot (compressed air optional)
 - Using a name-brand MicroSD chip (SanDisk works good in my experience)
 - If you are able to read the chip in the flipper before it stops working, maybe try updating (upload the update file to the card, and update from the file browser)

**Comment by dovydasa2** [comment]
Ama buy a better sd tomorrow

**Comment by WillyJL** [comment]
from that video, one of the sd cards is corrupted, and the other one doesnt have firmware files on it. choose one of the 2 sd cards, plug it into flipper, go to settings > storage > format sd card, format it there, then reinstall the firmware with either webupdater, or qflipper, or mobile app.

**Comment by dovydasa2** [comment]
Tried formating both didn't work

**Comment by WillyJL** [comment]
did you reinstall the firmware as i told you to do?

**Comment by dovydasa2** [comment]
How to do that and how do you know that one is corrupted and the other one dosent have frimware

**Comment by WillyJL** [comment]
the flipper literally tells you. but you refuse to read.
it tells you that the app cannot run, and you need to reinstall firmware.
the other one tells you that it is a bad sd card, so either badly formatted or corrupted.
in any case, both of those are fixed by format + reinstall firmware.
reinstall firmware just means install firmware again. currently, its like you are mising a part of the firmware.
just install using any of the supported installation methods. qflipper, webupdater, mobile app... like i already told you.

**Comment by dovydasa2** [comment]
i got a new Sd ama reply in a minute if the glitch still works

**Comment by dovydasa2** [comment]
everythings works just fine thanks for the help
