### ISSUE TITLE
question

### ISSUE THREAD

**Issue by dovydasa2** [Next-Flip/Momentum-Firmware#335]
can you and how can you add more things like bad usb ect ect.

**Comment by WillyJL** [comment]
duplicate of #334 . no.

**Comment by Choder7** [comment]
You need to manually add them to your Flipper via computer and a cable or your phone.

You can find many online, download them and then use qFlipper on PC or the Flipper mobile app on your smartphone.

**On your phone,**
go into options, turn on experimental features and click on file manager, then click on ext (external).

Then in the badusb folder you can add the files.


**For PC** just connect your Flipper and click on the files tab in qFlipper.
