### ISSUE TITLE
Duckyscript in general.

### ISSUE THREAD

**Issue by GameLord2011** [Next-Flip/Momentum-Firmware#336]
### Describe the enhancement you're suggesting.

I think you could add more Duckyscript features. My ideas include:
- F13-F24 Keys (See [ThioJoe/F-Key-Sender](https://www.github.com/ThioJoe/F-Key-Sender))
- OS Detection
- Conditional Loops
- Loot Folder (Make use of usb protocol being two-way VIA using CapsLock as a one and NomLock as zero, Exports in raw text.)

### Anything else?

Nope.

**Comment by WillyJL** [comment]
- f13-f24 already exists.
- how on earth would os detection work?
- duckyscript is only for quick scripting. If you need a Turing complete language and loops and all of that, Use badusb through JavaScript.
- receiving data via capslock and numlock is both slow and os dependent. You need a counterpart on the target pc encoding the data in capslock. Providing this as part of badusb is not feasible, that's something you'd need to do in your own script. And at that point, you can literally already do this with JavaScript: there is mass storage with the usbdisk module and the badusb module, type a script with badusb into the pc that waits for a usb drive with correct name to show up, then move files to it, after typing this script into the pc stop badusb and start mass storage, the script will detect it and move data over. There are so many scripts like this available in our discord and online too most likely
