### ISSUE TITLE
SubGHz: Expansion/VGM support

### ISSUE THREAD

**Issue by HaxSam** [Next-Flip/Momentum-Firmware#5]
### Description of the feature you're suggesting.

With the new API in expansion in the [merge,](https://github.com/Next-Flip/Momentum-Firmware/pull/6) it will be possible to use the VGM in SubGHz without any bugs.

Todo is refactoring the GPS usage in SubGHz:
- [x] Merge the init+start and deinit+stop functions, and in start check for expansion is connected.
- [x] On app start, it will try to start if baud rate is set, will work only if no expansion is connected.
- [x] When baud rate changed for GPS in settings, change them and store also start GPS when baud rate was 0/off before only when no expansion is connected.
- [x] Delete GPS instance only when it got initialized. `subghz->gps`
- [x] everywhere else in the app, it might check for baud rate being set in order to display satellite info. Instead, check for GPS being initialized

**Comment by WillyJL** [comment]
Fix was released in [mntm-002](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-002)
