### ISSUE TITLE
NRF24 not working

### ISSUE THREAD

**Issue by AH2005NA** [Next-Flip/Momentum-Firmware#50]
### Describe the bug.

NRF24 is not working the only thing that helpt was downgreading

### Reproduction

go to the nrf24 app

**Comment by WillyJL** [comment]
Downgrading to what? What do you have in momentum > protocols > gpio pins > nrf24? And what nrf24 board is it?

**Comment by AH2005NA** [comment]
I downgraded it to the officiall version from Flipper. In the Settings in
NRF24 PSI is Default4(but i already testet it with Extra7). Its an custom
nrf24 i created by myself(I already testet it with an other Flipper). Here
is the schema:
[image: image.png]

WillyJL ***@***.***> schrieb am Fr., 22. März 2024, 18:47:

**Comment by WillyJL** [comment]
works fine here. please show exactly how its connected physically (photo, not schematic), and double check your settings. do so after reinstalling momentum, on dev branch (see webupdater)

**Comment by AH2005NA** [comment]
I copied the apps from an other Flipper and it works now. 😎

**Comment by WillyJL** [comment]
I assume something went wrong during your install process then
