### ISSUE TITLE
Universal remotes bug

### ISSUE THREAD

**Issue by sobakintech** [Next-Flip/Momentum-Firmware#57]
The universal remotes take long to load, i did not encounter this in any other firmwares. Is this normal?

**Comment by WillyJL** [comment]
Define "long". And compare to the latest dev branch of the other firmwares, there's been changes to how they're loaded recently from upstream.

**Comment by sobakintech** [comment]
On other firmwares it loads instantly, on momentum, it takes about 5-10 seconds to load.

**Comment by WillyJL** [comment]
Please, I asked you what firmwares, and to compare the speeds with the latest version of those firmware(s)' dev branch.

**Comment by SuperJakov** [comment]
> On other firmwares it loads instantly, on momentum, it takes about 5-10 seconds to load.

This is not a bug, it is slower by just a bit.

It loads in 2 seconds for me

**Comment by WillyJL** [comment]
don't really see how this could be so dramatic. the universal remotes files on momentum, like on other CFW, contain more assets, so they are larger, and might take slightly longer. if comparing directly to a previous behavior on momentum and it is slower, only reason i could see is the recent refactor of some infrared worker aspects, but i didnt notice any significant impact, it takes just a couple of short seconds. check your sd card maybe, or provide more detailed info please.
