### ISSUE TITLE
JS: Random function in Math library not working right.

### ISSUE THREAD

**Issue by corrupt3k** [Next-Flip/Momentum-Firmware#61]
### Describe the bug.

Generating random numbers within a defined range is not working. Numbers are generated outside of the range sometimes.

### Reproduction

let math = require("math");

function getRandomArbitrary(min, max) {
    return math.floor(math.random() * (max - min + 1)) + min;
}

while (1 === 1) {
	let randomIndex = getRandomArbitrary(0, 23);
	print(randomIndex);
	delay(1000);
}

**Comment by SuperJakov** [comment]
By running this script:
```javascript
let math = require("math")

while (true) {
print(math.random())
delay(500)
}
```

We can see that sometimes, it returns values higher than 1

Devbuild version: momentum dev c633b0f3 1st April of 2024

**Comment by WillyJL** [comment]
can you check on #67 ?

**Comment by WillyJL** [comment]
Fix was released in [mntm-002](https://github.com/Next-Flip/Momentum-Firmware/releases/tag/mntm-002)
