### ISSUE TITLE
Bluetooth doesnt work.

### ISSUE THREAD

**Issue by cyb3rsalih** [Next-Flip/Momentum-Firmware#66]
### Describe the bug.

I installed firmware from web. Even bluetooth is on, none of my device see it

### Reproduction

1- Install the latest firmware from web
2- Open bluetooth from device
3- You can't see it from other devices.

Currently I tried it from M1 Macbook Air and iPhone 11

**Comment by WillyJL** [comment]
correct, they should not see it. use the mobile app.
