### ISSUE TITLE
flipper zero pocsag firmware corrupt

### ISSUE THREAD

**Issue by sysadminpower2019** [Next-Flip/Momentum-Firmware#74]
### Describe the bug.

Hello when i use the pocsag pager with the hamradio network all i get is corrupted data. See screenshot. I'm not sure what to try

### Reproduction

Try to receive a message
![Screenshot_20240404-174849_Flipper](https://github.com/Next-Flip/Momentum-Firmware/assets/40726534/4807a82f-4208-40fc-ad19-700c8a8039ba)

**Comment by WillyJL** [comment]
Did it give an api mismatch message?

**Comment by sysadminpower2019** [comment]
Where would i check that?

**Comment by WillyJL** [comment]
opening the app it would say "app too new" or "firmware too new" or something like that, showing 2 api versions.

**Comment by sysadminpower2019** [comment]
I dont see anything like that. looking at the info it says version 0.1 
developed by xmasterx and shmuma but thats about it

**Comment by WillyJL** [comment]
cant replicate. the app (from lab.flipper.net, this is not an app we include in momentum) works fine on my end. maybe it is simply that your pocsag message is jumbled data and the app cannot show it correctly. or maybe it is a very old version left from some other firmware / other tiem you installed it, i remember a bug like that 1+ year ago.

also, there is no need to use the dedicated app. momentum includes the pocsag protocol inside the main subghz app. i just tested and the same messages are received by the pocsag app and momentum's subghz app.

pocsag pager app from lab.flipper.net:
![image](https://github.com/Next-Flip/Momentum-Firmware/assets/49810075/6e442d56-52e8-46ba-8c79-f4c6c96b6e4a)

subghz app in momentum (remember to configure correct modulation (usually FM95 works) and frequency!)
![image](https://github.com/Next-Flip/Momentum-Firmware/assets/49810075/1c91ae28-f9ed-4dfd-976b-f5a6f4d54b83)
