### ISSUE TITLE
Adding two new .ir files to inflared folder and two new .txt remotes base on those

### ISSUE THREAD

**Issue by viralatadr** [Next-Flip/Momentum-Firmware#78]
### Describe the enhancement you're suggesting.

Hi, i just recently find and create two new .ir files for two Washlet/Bidet brands and also create two remotes for those file to put in inflared/remote. Is there a way that this could be part of Momentum? 

![Screenshot-20240405-075555](https://github.com/Next-Flip/Momentum-Firmware/assets/9348511/8a939117-9247-40d2-9c1a-b7ffb302fe27)

![Screenshot-20240405-075409](https://github.com/Next-Flip/Momentum-Firmware/assets/9348511/9158aa1d-1c43-4674-8fd9-ae9afbc3d003)

![Screenshot-20240405-075345](https://github.com/Next-Flip/Momentum-Firmware/assets/9348511/e73d0f84-2419-4de9-9f6c-2f9acaa50669)

**Comment by viralatadr** [comment]
.

**Comment by WillyJL** [comment]
we don't want to include extra files by default, we are a firmware after all. we only include example files typically, and for ir that is the samsung remote. IIRC this was part of a bounty on our discord, i suggest you share them in the script sharin channel, and maybe contribute to a file dump like uberguidoz'

**Comment by viralatadr** [comment]
Got it

**Comment by viralatadr** [comment]
I had never done a pull request bofore. Today i did two. It was fun. Thank you for the recomendation. Now lets see if they aprove it.

**Comment by viralatadr** [comment]
> we don't want to include extra files by default, we are a firmware after all. we only include example files typically, and for ir that is the samsung remote. IIRC this was part of a bounty on our discord, i suggest you share them in the script sharin channel, and maybe contribute to a file dump like uberguidoz'

Did it in the Uberguidoz and logickworkshop repo

**Comment by WillyJL** [comment]
nice!
