### ISSUE TITLE
[MAYHEM] Evil Portal does not function as intended in [MAYHEM] Marauder app 

### ISSUE THREAD

**Issue by dav3shanahan** [Next-Flip/Momentum-Firmware#81]
### Describe the bug.

evil portal within the marauder app does not set up a portal, just gets stuck on the command or if I choose a prebuilt portal, the flipper crashes and reboots says "out of memory" when I attempt to set html manually, flipper crashes and reboots. I tried all of the other [mayhem] apps and they all work as designed (camera, qr code, morse flasher, nanny cam and motion detector), marauder also allows me to scan for wifi networks, jjust can't seem to get evil portal to work lately. Am I missing something
![IMG_5428](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/66f532e1-d0cc-4441-bc2a-41423adb652e)
![IMG_5429](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/0cc7717a-0f56-4583-802f-b7af456ab75b)
![IMG_5430](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/7e3f0018-1ec0-42b5-b601-e2d42d1027b6)
![IMG_5432](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/27727fc5-2274-48d2-8d41-a7f02855a33b)
![IMG_5433](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/59cfc90a-b59c-45cb-b048-182284f146ef)
![IMG_5431](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/c659b76c-879d-47dd-8adc-21f0356e1485)
![IMG_5434](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/e1238ca4-4de5-480e-846b-6c0f97d5097f)
![IMG_5428](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/b696ea48-d6c9-43e0-9a96-9950d99e4880)
![IMG_5429](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/c7411be8-6c7f-4ba9-b5f6-56fddc43b213)
![IMG_5430](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/46b252cb-3667-4ebe-8f77-4de27337368f)
![IMG_5432](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/9a1d1b85-bc2b-4f49-a2ce-c2bd1f62a5cd)
![IMG_5433](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/26736853-3ca8-40ab-9e9c-5752d87226ce)
![IMG_5431](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/f088d4dd-9d2a-4f24-b411-e252d0af3ab9)
![IMG_5434](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/a9e0046c-0f33-4b33-83ac-7b70d69707b7)

### Reproduction

Turn flipper on, navigate to [mayhem] marauder, scroll down to evil portal, when i go to set html, flipper zero crashes and reboots. sometimes the html is displayed out on the flipper zero. see attached images for some of the messages that i receive
![IMG_5428](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/3a055515-d030-4b7e-9f46-c16b72a22f0e)
![IMG_5429](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/d92f376a-9233-4a4b-b93a-062598796390)
![IMG_5430](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/89562cef-39aa-41ac-aa80-527b295de577)
![IMG_5432](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/8235f249-d4cf-4e79-b148-ddcef76fad9a)
![IMG_5433](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/7015b063-efcb-45d1-9948-bcdd2b7dc8fb)
![IMG_5431](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/830e76e7-0735-40e0-a7c4-ceb08231b522)
![IMG_5434](https://github.com/Next-Flip/Momentum-Firmware/assets/46032712/eef96af8-5c04-4f76-a46f-1d0a92a5582c)

**Comment by jetlagv1** [comment]
Put the ap.config.txt and index.html file in the root of the sd card on the esp cam itself.
The ap.config.txt file has to be in the root of the esp sd slot. After you are able to select different index.html files through the "Load Evil Portal HTML file" in the maurauder app. Before switching between html files reboot.
