### ISSUE TITLE
BLE SPam freeze when set personalised name in flipper-z-f7-update-mntm-dev-9b3f7f49

### ISSUE THREAD

**Issue by mero20j1** [Next-Flip/Momentum-Firmware#90]
### Describe the bug.

WHen i set the name in BT Settings Flood the app frezze

### Reproduction

I try reboot many times, its work fine if is set to ramdom

### Target

flipper-z-f7-update-mntm-dev-9b3f7f49

**Comment by WillyJL** [comment]
Fixed in dev build a few days ago, thanks for the report
