### ISSUE TITLE
BT Spam Apple Vision Pro selection or "Advanced BT Profile selctor"

### ISSUE THREAD

**Issue by NF8C** [Next-Flip/Momentum-Firmware#91]
### Description of the feature you're suggesting.

BLE Spam should have a way to pop up the Apple Vision pro so we can see everyone's head spin to find where the Apple Vision Pro is in the crowd.  There is currently no way to select it specifically to create spam BT notifications.  Some may even want an "advanced device selector" to spam pairing requests for other specific devices.

### Anything else?

Love the work so far!

**Comment by WillyJL** [comment]
> There is currently no way to select it specifically to create spam BT notifications

me when "hold ok on the attack"
