### ISSUE TITLE
Bluetooth not working

### ISSUE THREAD

**Issue by doshiujjwal** [Next-Flip/Momentum-Firmware#93]
### Describe the bug.

The mobile is not able to detect the flipper. The device is not shown in the Bluetooth device list. 
Once I flashed the default firmware it's detected by the mobile device.

### Reproduction

Just flash the firmware and go to the mobile phone to connect it with the mobile app, the device will not be connected and in the Bluetooth settings of the mobile device flipper will not be visible.

**Comment by WillyJL** [comment]
It is normal to not be visible in phone settings. For flipper app, you need to click forget, then connect again.
