### ISSUE TITLE
The light does not turn off.

### ISSUE THREAD

**Issue by NunoFilipePereira** [Next-Flip/Momentum-Firmware#95]
### Describe the bug.

The light does not turn off mesoq ue is stinky for this. I already updated 3 times but the problem continues. In this way the battery loses performance and it is not very attractive to always walk with the light access.

### Reproduction

.

### Target

.

### Logs

```Text
.
```

### Anything else?

.

**Comment by ZProLegend007** [comment]
The backlight? Check your display backlight timeout setting numpty XD

If it's the LED and you've updated before it could be a hardware issue. Have you tried resetting?

**Comment by NunoFilipePereira** [comment]
Yes . I already tried to redefenir. Change from firmware to another and Ecran erases. but with this not.

**Comment by WillyJL** [comment]
@NunoFilipePereira momentum > misc > screen > rgb backlight OFF. It explicitly asked you if you had installed the hardware mod for rgb backlight when you enabled it. You do not have the hardware modification but still enabled it. What did you think was going to happen?
